import PDFDocument from "pdfkit";
import { getModel } from "../utils/model.js";
import fs from "fs";
import path from "path";

import { uploadToS3 } from "../utils/uploadToS3.js";
import { getDownloadUrl } from "../utils/getDownloadUrl.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";
import { deductCredits } from "../utils/deductCredits.js";

export const pdfAgent = async (state) => {

  try {
await checkAgentLimit(
    state.userId,
    "pdf"
  );
 await deductCredits(

        state.userId,

        "pdf"

    );  
    const llm =
      getModel("pdf", state.model);

    const aiResponse =
      await llm.invoke(`

Create a professional document about:

${state.prompt}

Rules:

- Generate a professional title.
- Generate introduction.
- Generate multiple sections.
- Generate bullet points where required.
- Generate conclusion.
- No markdown.
- No code blocks.
- No ** symbols.
- No ### headings.
- Return plain text only.

`);

    const rawContent =
      aiResponse?.content?.trim() ||
      state.prompt;

    const lines =
      rawContent
        .split("\n")
        .filter(line => line.trim());

    const generatedTitle =
      lines?.[0]?.length < 120
        ? lines[0]
        : state.prompt;

    const cleanContent =
      rawContent
        .replace(/\*\*/g, "")
        .replace(/```/g, "")
        .replace(/###/g, "")
        .replace(/##/g, "")
        .replace(/#/g, "")
        .trim();

    const fileName =
      `pdf-${Date.now()}.pdf`;

    const doc =
      new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true,
        info: {
          Title: generatedTitle,
          Author: "Aether",
          Subject: state.prompt,
          Creator: "Aether PDF Agent"
        }
      });

    const chunks = [];

    doc.on("data", chunk => {
      chunks.push(chunk);
    });

    // Cover Title

    doc
      .fontSize(26)
      .fillColor("#111827")
      .text(
        generatedTitle,
        {
          align: "center"
        }
      );

    doc.moveDown();

    doc
      .fontSize(10)
      .fillColor("#6B7280")
      .text(
        `Generated on ${new Date().toLocaleString()}`,
        {
          align: "center"
        }
      );

    doc.moveDown(3);

    // Content

    doc
      .fontSize(12)
      .fillColor("#374151")
      .text(
        cleanContent,
        {
          align: "left",
          lineGap: 6
        }
      );

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#9CA3AF")
      .text(
        "Generated by Aether",
        {
          align: "center"
        }
      );

    doc.end();

    await new Promise(
      (resolve, reject) => {

        doc.on(
          "end",
          resolve
        );

        doc.on(
          "error",
          reject
        );

      }
    );

    const pdfBuffer =
      Buffer.concat(chunks);

    let downloadUrl;
    let localFallbackUsed = false;
    try {
      await uploadToS3(
        pdfBuffer,
        fileName,
        "application/pdf"
      );

      downloadUrl = await getDownloadUrl(
        fileName,
        24*60*60
      );
    } catch (s3Error) {
      console.warn("⚠️ S3 Upload/URL sign failed. Falling back to local storage:", s3Error.message);
      if (!fs.existsSync("uploads")) {
        fs.mkdirSync("uploads");
      }
      fs.writeFileSync(path.join("uploads", fileName), pdfBuffer);
      downloadUrl = `${state.gatewayUrl || "http://localhost:8000"}/api/agent/uploads/${fileName}`;
      localFallbackUsed = true;
    }

    return {
      ...state,
      response: `
# ✅ PDF Generated Successfully

📄 **${generatedTitle}**

📥 [Download PDF](${downloadUrl})

${localFallbackUsed ? "⚠️ *Note: Served from dynamic microservice storage due to S3 configurations.*" : "⏳ *Link expires in 24 hours.*"}
`.trim()
    };

  } catch (error) {

    console.log(
      "PDF Agent Error:",
      error
    );

    return {

      ...state,

      response:
        "❌ Failed to generate PDF."

    };

  }

};